name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webiny/action-conventional-commits@v1.0.3
    - name: add nightly toolchain
      run: rustup update nightly
    - name: Format code
      run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu && cargo +nightly fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --bins --tests --examples --all -- -D warnings
    - name: Run tests
      run: cargo test --verbose
